language: node_js
sudo: 'false'
before_script: []
env:
  global:
    - secure: >-
        A2qs3wNbOPxyv1q0b81OqAx6OW0gNRe52iJxoP+sol6TnJQ9l7Cc9BKCyz2A34mCuy709uU1mbAqkPk8x8Z6N+913NNHk9guQnaIXhuhRoOgJBSKwXdB8ers39OnUcgICpmuFl7W+MKbpUC6KlaOFRYtDlLFen1oXP+RuKoqeUo=
    - secure: >-
        c+nlhWxI7i/nZru/89ZhUKWzBfssLflGDX4LQbkkfW5kpk9guAw3QacUW/c9lwRCHf3DjuZKCreuJ621ALqX8UbAkPc6sjy48MXQJcQY8t7wdc9TTe3bKdzpJGBAE4GP7hToYjUXV98fev6IZlEt6vi/acyLTOeQ1gvmmKR4Kz8=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
install:
  - npm install -g polymer-cli
  - polymer install --variants
cache:
  directories:
    - node_modules
